Database Implementation Techniques Programming Task SoSe2013: main.cpp File Reference
main.cpp File Reference
#include <string>
#include <core/global_definitions.hpp>
#include <core/base_column.hpp>
#include <core/column_base_typed.hpp>
#include <core/column.hpp>
#include <core/compressed_column.hpp>
#include <compression/dictionary_compressed_column.hpp>
Functions
bool unittest (boost::shared_ptr< ColumnBaseTyped< int > > ptr)
bool unittest (boost::shared_ptr< ColumnBaseTyped< float > > ptr)
bool unittest (boost::shared_ptr< ColumnBaseTyped< std::string > > ptr)
int main ()
Function Documentation
int main ()
Definition at line 18 of file main.cpp.
References CoGaDB::FLOAT, CoGaDB::INT, unittest(), and CoGaDB::VARCHAR.
bool unittest (boost::shared_ptr< ColumnBaseTyped< int > > ptr)
Definition at line 13 of file unittest.cpp.
Referenced by main().
bool unittest (boost::shared_ptr< ColumnBaseTyped< float > > ptr)
Definition at line 144 of file unittest.cpp.
bool unittest (boost::shared_ptr< ColumnBaseTyped< std::string > > ptr)
Definition at line 305 of file unittest.cpp.
References getRandomString().