Database Implementation Techniques Programming Task SoSe2013: unittest.cpp File Reference
unittest.cpp File Reference
#include <string>
#include <core/global_definitions.hpp>
#include <core/base_column.hpp>
#include <core/column_base_typed.hpp>
#include <core/column.hpp>
#include <core/compressed_column.hpp>
#include <compression/dictionary_compressed_column.hpp>
Functions
bool unittest (boost::shared_ptr< ColumnBaseTyped< int > > col)
bool unittest (boost::shared_ptr< ColumnBaseTyped< float > > col)
const std::string getRandomString ()
bool unittest (boost::shared_ptr< ColumnBaseTyped< std::string > > col)
Function Documentation
const std::string getRandomString ()
Definition at line 279 of file unittest.cpp.
Referenced by unittest().
bool unittest (boost::shared_ptr< ColumnBaseTyped< int > > col)
Definition at line 13 of file unittest.cpp.
Referenced by main().
bool unittest (boost::shared_ptr< ColumnBaseTyped< float > > col)
Definition at line 144 of file unittest.cpp.
bool unittest (boost::shared_ptr< ColumnBaseTyped< std::string > > col)
Definition at line 305 of file unittest.cpp.
References getRandomString().